"""Unit 3 — the newsletter brand strings (title / footer / subject_format).

All three are optional. The load-bearing test in this module is
``test_newsletter_defaults_when_block_absent``: with no ``newsletter:`` block in
sections.yaml the rendered HTML must be **byte-for-byte** what the pipeline
produced before the strings were configurable. ``tests/goldens/`` holds that
output, captured from the pre-change code.

Two things are frozen so the comparison is honest rather than lucky:

* ``passband.render`` calls ``datetime.now()`` internally with no injection seam, so
  the tests patch the module's ``datetime`` name. Without it the golden would
  rot every midnight.
* Every expected date string is derived with the same ``strftime`` call the code
  uses, never hardcoded as ``"Aug 13"`` — both format strings are locale
  sensitive and nothing in the pipeline pins ``LC_TIME``.

No network, no filesystem outside ``tmp_path`` and the read-only golden.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pytest

from passband import render as render_mod
from passband.config import config
from passband.curate import Brief
from passband.render import (
    format_subject,
    newsletter_brand,
    render_newsletter,
)

# The literal strings this unit moved into config. Spelled out here on purpose:
# asserting against passband.render's constants would let a typo in the source
# silently redefine "the default" and the regression guard would pass anyway.
CURRENT_TITLE = "Risk & Signals Digest"
CURRENT_FOOTER = "Generated by Passband — a self-hosted RSS digest pipeline."
CURRENT_SUBJECT_FORMAT = "{title} — {date:%b %d}"  # U+2014 EM DASH

GOLDEN = Path(__file__).parent / "goldens" / "newsletter_default.html"

# Arbitrary but fixed. The golden was rendered at this instant.
FIXED_NOW = datetime(2026, 8, 13, 7, 30, 0)


@pytest.fixture
def frozen_clock(monkeypatch):
    """Pin ``datetime.now()`` inside passband.render to FIXED_NOW."""

    class _Frozen:
        @staticmethod
        def now():
            return FIXED_NOW

    monkeypatch.setattr(render_mod, "datetime", _Frozen)
    return FIXED_NOW


def golden_sections() -> list[dict]:
    """The exact section payload the committed golden was rendered from.

    Covers both branches of every ``{% if %}`` in TEMPLATE: an alert section and
    a plain one, a section with a note and one without, a brief with sources and
    one without, and a title containing ``&`` so the autoescape behaviour is
    part of the frozen bytes.
    """
    return [
        {
            "title": "Alerts",
            "alert": True,
            "briefs": [
                Brief(
                    title="M5.8 quake offshore",
                    body="Shallow event, no damage reported.",
                    url="https://example.invalid/a",
                    sources=["USGS"],
                ),
            ],
        },
        {
            "title": "Top News",
            "note": "rotating deep dive",
            "briefs": [
                Brief(title="Headline one", body="Body one.",
                      url="https://example.invalid/1",
                      sources=["Wire", "Paper"]),
                Brief(title="Headline two & more", body="Body two.",
                      url="https://example.invalid/2", sources=[]),
            ],
        },
    ]


def write_sections(config_dir, newsletter: dict | None) -> None:
    """Write a minimal sections.yaml, optionally carrying a newsletter block."""
    doc: dict = {"rotation": {"slots_per_day": 2}}
    if newsletter is not None:
        doc["newsletter"] = newsletter
    doc["sections"] = [{"id": "global", "title": "Top News", "cadence": "daily"}]
    config_dir.write("sections.yaml", doc)


# ---------------------------------------------------------------------------


def test_newsletter_defaults_when_block_absent(config_dir, frozen_clock):
    """No newsletter block -> today's title, footer and subject, byte for byte."""
    write_sections(config_dir, None)

    cfg = config()
    # An absent block is an empty mapping, never a KeyError and never None.
    assert cfg["newsletter"] == {}

    title, footer, subject_format = newsletter_brand(cfg)
    assert title == CURRENT_TITLE
    assert footer == CURRENT_FOOTER
    assert subject_format == CURRENT_SUBJECT_FORMAT

    # Derived, not hardcoded: %b is locale sensitive.
    assert format_subject(subject_format, title, FIXED_NOW) == \
        f"{CURRENT_TITLE} — {FIXED_NOW:%b %d}"

    html = render_newsletter(title, golden_sections(),
                             header_note="Forecast: sunny, high 92.",
                             footer=footer)
    assert html == GOLDEN.read_text(encoding="utf-8")


def test_title_from_config_used_in_subject(config_dir, frozen_clock):
    """A configured title reaches both the subject line and the HTML."""
    write_sections(config_dir, {"title": "Acme Wire"})

    cfg = config()
    title, footer, subject_format = newsletter_brand(cfg)
    assert title == "Acme Wire"
    # The two strings that were NOT configured keep their defaults.
    assert footer == CURRENT_FOOTER
    assert subject_format == CURRENT_SUBJECT_FORMAT

    subject = format_subject(subject_format, title, FIXED_NOW)
    assert subject == f"Acme Wire — {FIXED_NOW:%b %d}"
    assert CURRENT_TITLE not in subject

    html = render_newsletter(title, golden_sections(), footer=footer)
    assert "<title>Acme Wire</title>" in html
    assert CURRENT_TITLE not in html


def test_subject_format_override(config_dir, frozen_clock):
    """A custom subject_format is honoured, including its date spec."""
    write_sections(config_dir, {
        "title": "Acme Wire",
        "subject_format": "[{date:%Y-%m-%d}] {title}",
    })

    title, _footer, subject_format = newsletter_brand(config())
    assert subject_format == "[{date:%Y-%m-%d}] {title}"
    assert format_subject(subject_format, title, FIXED_NOW) == \
        "[2026-08-13] Acme Wire"


def test_footer_rendered_in_html(config_dir, frozen_clock):
    """A configured footer replaces the shipped one in the rendered HTML."""
    write_sections(config_dir, {"footer": "Sent by Acme. Reply to unsubscribe."})

    title, footer, _fmt = newsletter_brand(config())
    assert footer == "Sent by Acme. Reply to unsubscribe."

    html = render_newsletter(title, golden_sections(), footer=footer)
    assert "Sent by Acme. Reply to unsubscribe." in html
    assert "Generated by Passband" not in html
    # The footer keyword must not disturb the paragraph that carries it.
    assert ('<p style="color:#a1a1aa;font-size:11px;border-top:1px solid '
            '#e4e4e7;padding-top:12px;">') in html


def test_render_newsletter_escapes_title(frozen_clock):
    """Config-sourced strings are still escaped by Jinja on the way in.

    Title and footer now both originate in a YAML file, so a stray ``&`` or an
    injected tag must not reach the recipient's mail client as markup.
    """
    html = render_newsletter(
        '<script>alert("x")</script> R&D "quotes"',
        golden_sections(),
        footer='<b>bold</b> & dangerous',
    )

    assert "<script>" not in html
    assert "&lt;script&gt;alert(&#34;x&#34;)&lt;/script&gt; R&amp;D" in html
    assert "<b>bold</b>" not in html
    assert "&lt;b&gt;bold&lt;/b&gt; &amp; dangerous" in html


def test_malformed_subject_format_falls_back_to_default(config_dir, frozen_clock):
    """Beyond the plan's table: a bad format string must never abort a send.

    ``str.format`` raises KeyError/ValueError on an unknown field or an
    unbalanced brace. main.py builds the subject *after* writing the HTML to
    disk but *before* handing it to Resend, so an unguarded raise loses the send
    while leaving a rendered file behind.
    """
    write_sections(config_dir, {"subject_format": "{titel} on {date:%b %d}"})

    title, _footer, subject_format = newsletter_brand(config())
    assert format_subject(subject_format, title, FIXED_NOW) == \
        f"{CURRENT_TITLE} — {FIXED_NOW:%b %d}"

    # Unbalanced brace takes the same path.
    assert format_subject("{title", title, FIXED_NOW) == \
        f"{CURRENT_TITLE} — {FIXED_NOW:%b %d}"
