"""Render the newsletter HTML from curated section briefs."""
from __future__ import annotations

from datetime import datetime

from jinja2 import Environment, BaseLoader

from .curate import Brief

TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ title }}</title></head>
<body style="margin:0;background:#f4f4f5;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#18181b;">
<div style="max-width:680px;margin:0 auto;padding:24px;">
  <h1 style="font-size:22px;margin:0 0 4px;">{{ title }}</h1>
  <p style="color:#71717a;font-size:13px;margin:0 0 {% if header_note %}4px{% else %}24px{% endif %};">{{ date }}</p>
  {% if header_note %}<p style="color:#52525b;font-size:13px;margin:0 0 24px;">{{ header_note }}</p>{% endif %}
  {% for section in sections %}
  <div style="margin:0 0 28px;{% if section.alert %}background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px 16px;{% endif %}">
    <h2 style="font-size:16px;text-transform:uppercase;letter-spacing:.04em;color:{% if section.alert %}#b91c1c{% else %}#3f3f46{% endif %};border-bottom:2px solid {% if section.alert %}#fecaca{% else %}#e4e4e7{% endif %};padding-bottom:6px;margin:0 0 12px;">{{ section.title }}</h2>
    {% if section.note %}<p style="font-size:12px;color:#71717a;margin:-6px 0 12px;">{{ section.note }}</p>{% endif %}
    {% for b in section.briefs %}
    <div style="margin:0 0 14px;">
      <a href="{{ b.url }}" style="font-size:15px;font-weight:600;color:#1d4ed8;text-decoration:none;">{{ b.title }}</a>
      <p style="font-size:14px;line-height:1.5;margin:4px 0 2px;">{{ b.body }}</p>
      {% if b.sources %}<p style="font-size:12px;color:#a1a1aa;margin:0;">{{ b.sources|join(' · ') }}</p>{% endif %}
    </div>
    {% endfor %}
  </div>
  {% endfor %}
  <p style="color:#a1a1aa;font-size:11px;border-top:1px solid #e4e4e7;padding-top:12px;">
    {{ footer }}</p>
</div></body></html>"""

# --------------------------------------------------------------------------
# Brand strings
#
# Configurable via the optional `newsletter:` block in config/sections.yaml.
# The defaults below are the strings that were hardcoded through 1.1.x, so an
# absent block reproduces the previous output byte for byte.
# --------------------------------------------------------------------------

DEFAULT_TITLE = "Risk & Signals Digest"
DEFAULT_FOOTER = "Generated by Passband — a self-hosted RSS digest pipeline."
DEFAULT_SUBJECT_FORMAT = "{title} — {date:%b %d}"  # U+2014 EM DASH


def newsletter_brand(cfg: dict) -> tuple[str, str, str]:
    """(title, footer, subject_format) from ``config()``.

    Each of the three keys is independently optional: a block that sets only
    `title` keeps the shipped footer and subject format. Empty or non-string
    values fall back too, so a stray `title:` with nothing after it (which YAML
    reads as None) cannot produce a blank subject line.
    """
    block = cfg.get("newsletter") or {}
    if not isinstance(block, dict):
        block = {}

    def pick(key: str, default: str) -> str:
        value = block.get(key)
        return value if isinstance(value, str) and value.strip() else default

    return (pick("title", DEFAULT_TITLE),
            pick("footer", DEFAULT_FOOTER),
            pick("subject_format", DEFAULT_SUBJECT_FORMAT))


def format_subject(subject_format: str, title: str, date: datetime) -> str:
    """Build the email subject, tolerating a malformed format string.

    A user-supplied format reaches ``str.format``, which raises on an unknown
    field name or an unbalanced brace. main.py builds the subject *after* the
    HTML has been written to disk and *before* the send, so an unguarded raise
    would lose the day's newsletter over a typo. Complain and fall back to the
    default *format* — the configured title is still honoured.
    """
    try:
        return subject_format.format(title=title, date=date)
    except (KeyError, IndexError, ValueError, TypeError, AttributeError) as exc:
        print(f"render: ignoring malformed subject_format {subject_format!r} "
              f"({exc}); using the default")
        return DEFAULT_SUBJECT_FORMAT.format(title=title, date=date)


def render_newsletter(title: str, sections: list[dict],
                      header_note: str | None = None,
                      footer: str = DEFAULT_FOOTER) -> str:
    """sections: [{"title": str, "briefs": list[Brief]}], pre-filtered to non-empty."""
    env = Environment(loader=BaseLoader(), autoescape=True)
    tmpl = env.from_string(TEMPLATE)
    return tmpl.render(
        title=title,
        date=datetime.now().strftime("%A, %B %d, %Y"),
        header_note=header_note,
        footer=footer,
        sections=sections,
    )
